### ISSUE TITLE
versioncomparisions are currently failing on Puppet 4 / strict

### ISSUE THREAD

**Issue by igalic** [puppet-community/puppet-mcollective#266]
```
Failures:

  1) mcollective should contain Class[mcollective]
     Failure/Error: it { should contain_class('mcollective') }
     
     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef at /home/travis/build/puppet-community/puppet-mcollective/spec/fixtures/modules/mcollective/manifests/defaults.pp:8:6 on node testing-worker-linux-docker-54f46fad-3199-linux-2.prod.travis-ci.org
     # ./vendor/bundle/ruby/2.1.0/gems/puppet-4.3.1/lib/puppet/pops/functions/dispatcher.rb:37:in `dispatch'
     # ./vendor/bundle/ruby/2.1.0/gems/puppet-4.3.1/lib/puppet/pops/functions/function.rb:44:in `call'
 ```

and, zooming in:

```
Error while evaluating a Function Call,
  'versioncmp' parameter 'a' expects a String value, got Undef
  at mcollective/manifests/defaults.pp:8:6 on node testing-worker-linux-docker
```

**Comment by rnelson0** [comment]
Strict can be annoying. The simple fix is to change line 8 `if versioncmp($::puppetversion, '4') < 0 {` to `if versioncmp("${::puppetversion}, '4') < 0 {  # lint:ignore:only_variable_string`. `puppetversion` is [no longer a core fact](https://docs.puppetlabs.com/facter/latest/core_facts.html) in facter 3, but it remains present in 2.4, so I'm not sure why it's empty in this case.

**Comment by igalic** [comment]
O_o

srsly??

why

**Comment by petems** [comment]
The requirement is that we need to add facts for puppetversion and facter version:

```
  let :facts do
    {
      :puppetversion => Puppet.version,
      :facterversion => Facter.version
    }
  end
```

However, we then need to move all the code that actually is changed by those facts and put them into their own logic in the specs, defined on each version:

```ruby
let :facts do
    {
      :puppetversion => Puppet.version,
      :facterversion => Facter.version
    }
  end

  let :mcollective_config_path do
    case Puppet.version
    when /4/
      '/etc/puppetlabs/mcollective'
    else
      '/etc/mcollective'
    end
  end

  let :mcollective_core_libdir_path do
    case Puppet.version
    when /^4\.$/
      '/opt/puppetlabs/mcollective/plugins'
    else
      '#{}'
    end
  end

  let :mcollective_site_libdir_path do
    case Puppet.version
    when /^4\.$/
      '/opt/puppetlabs/mcollective/plugins'
    else
      '/usr/local/libexec/mcollective'
    end
  end
``` 

etc.

**Comment by petems** [comment]
@rnelson0 The puppetversion fact still exists, somehow it deaded when the original version of 4 came out, but seems resolved (https://tickets.puppetlabs.com/browse/PUP-4359).

The docs need updating for that it seems! :smile:

**Comment by petems** [comment]
PR for change #267
